@ECHO OFF

flac -d -f -s -o chrono_1_01.wav "Chrono Trigger Symphony Vol 1 (FLAC)\01 - A Premonition.flac"
flac -d -f -s -o chrono_1_02.wav "Chrono Trigger Symphony Vol 1 (FLAC)\02 - The Chrono Trigger Symphony.flac"
flac -d -f -s -o chrono_1_03.wav "Chrono Trigger Symphony Vol 1 (FLAC)\03 - Morning Glow.flac"
flac -d -f -s -o chrono_1_04.wav "Chrono Trigger Symphony Vol 1 (FLAC)\04 - Peaceful Days.flac"
flac -d -f -s -o chrono_1_05.wav "Chrono Trigger Symphony Vol 1 (FLAC)\05 - Green Memories.flac"
flac -d -f -s -o chrono_1_06.wav "Chrono Trigger Symphony Vol 1 (FLAC)\06 - Guardia_s Millennial Fair.flac"
flac -d -f -s -o chrono_1_07.wav "Chrono Trigger Symphony Vol 1 (FLAC)\07 - Gato_s Song.flac"
flac -d -f -s -o chrono_1_08.wav "Chrono Trigger Symphony Vol 1 (FLAC)\08 - Strange Occurences.flac"
flac -d -f -s -o chrono_1_09.wav "Chrono Trigger Symphony Vol 1 (FLAC)\09 - Yearnings of the Wind.flac"
flac -d -f -s -o chrono_1_10.wav "Chrono Trigger Symphony Vol 1 (FLAC)\10 - Good Night.flac"
flac -d -f -s -o chrono_1_11.wav "Chrono Trigger Symphony Vol 1 (FLAC)\11 - Secret Of The Forest.flac"
flac -d -f -s -o chrono_1_12.wav "Chrono Trigger Symphony Vol 1 (FLAC)\12 - Battle.flac"
flac -d -f -s -o chrono_1_13.wav "Chrono Trigger Symphony Vol 1 (FLAC)\13 - Guardia Castle - Pride _ Glory.flac"
flac -d -f -s -o chrono_1_14.wav "Chrono Trigger Symphony Vol 1 (FLAC)\14 - Huh.flac"
flac -d -f -s -o chrono_1_15.wav "Chrono Trigger Symphony Vol 1 (FLAC)\15 - The Cathedral.flac"
flac -d -f -s -o chrono_1_16.wav "Chrono Trigger Symphony Vol 1 (FLAC)\16 - A Prayer for the Wayfarer.flac"
flac -d -f -s -o chrono_1_17.wav "Chrono Trigger Symphony Vol 1 (FLAC)\17 - Light of Silence.flac"
flac -d -f -s -o chrono_1_18.wav "Chrono Trigger Symphony Vol 1 (FLAC)\18 - Boss Battle 1.flac"
flac -d -f -s -o chrono_1_19.wav "Chrono Trigger Symphony Vol 1 (FLAC)\19 - Frog_s Theme.flac"
flac -d -f -s -o chrono_1_20.wav "Chrono Trigger Symphony Vol 1 (FLAC)\20 - Fanfare 1.flac"
flac -d -f -s -o chrono_1_21.wav "Chrono Trigger Symphony Vol 1 (FLAC)\21 - The Trial.flac"
flac -d -f -s -o chrono_1_22.wav "Chrono Trigger Symphony Vol 1 (FLAC)\22 - The Hidden Truth.flac"
flac -d -f -s -o chrono_1_23.wav "Chrono Trigger Symphony Vol 1 (FLAC)\23 - Critical Moment.flac"

flac -d -f -s -o chrono_2_01.wav "Chrono Trigger Symphony Vol 2 (FLAC)\01 - A Desolate World.flac"
flac -d -f -s -o chrono_2_02.wav "Chrono Trigger Symphony Vol 2 (FLAC)\02 - Mystery from the Past.flac"
flac -d -f -s -o chrono_2_03.wav "Chrono Trigger Symphony Vol 2 (FLAC)\03 - Site 16.flac"
flac -d -f -s -o chrono_2_04.wav "Chrono Trigger Symphony Vol 2 (FLAC)\04 - Those Without the Will to Live.flac"
flac -d -f -s -o chrono_2_05.wav "Chrono Trigger Symphony Vol 2 (FLAC)\05 - Lavos_ Theme.flac"
flac -d -f -s -o chrono_2_06.wav "Chrono Trigger Symphony Vol 2 (FLAC)\06 - The Last Day of the World.flac"
flac -d -f -s -o chrono_2_07.wav "Chrono Trigger Symphony Vol 2 (FLAC)\07 - Johnny of the Robo Gang.flac"
flac -d -f -s -o chrono_2_08.wav "Chrono Trigger Symphony Vol 2 (FLAC)\08 - Bike Chase.flac"
flac -d -f -s -o chrono_2_09.wav "Chrono Trigger Symphony Vol 2 (FLAC)\09 - Robo_s Theme.flac"
flac -d -f -s -o chrono_2_10.wav "Chrono Trigger Symphony Vol 2 (FLAC)\10 - Derelict Factory.flac"
flac -d -f -s -o chrono_2_11.wav "Chrono Trigger Symphony Vol 2 (FLAC)\11 - Battle 2.flac"
flac -d -f -s -o chrono_2_12.wav "Chrono Trigger Symphony Vol 2 (FLAC)\12 - Fanfare 2.flac"
flac -d -f -s -o chrono_2_13.wav "Chrono Trigger Symphony Vol 2 (FLAC)\13 - At the End of Time.flac"
flac -d -f -s -o chrono_2_14.wav "Chrono Trigger Symphony Vol 2 (FLAC)\14 - Jolly Ol_ Spekkio.flac"
flac -d -f -s -o chrono_2_15.wav "Chrono Trigger Symphony Vol 2 (FLAC)\15 - Fanfare 3.flac"
flac -d -f -s -o chrono_2_16.wav "Chrono Trigger Symphony Vol 2 (FLAC)\16 - Creeping through the Sewers.flac"
flac -d -f -s -o chrono_2_17.wav "Chrono Trigger Symphony Vol 2 (FLAC)\17 - Boss Battle 2.flac"
flac -d -f -s -o chrono_2_18.wav "Chrono Trigger Symphony Vol 2 (FLAC)\18 - Primeval Mountain.flac"
flac -d -f -s -o chrono_2_19.wav "Chrono Trigger Symphony Vol 2 (FLAC)\19 - Ayla_s Theme.flac"
flac -d -f -s -o chrono_2_20.wav "Chrono Trigger Symphony Vol 2 (FLAC)\20 - Rhythm of Earth_ Wind_ and Sky.flac"
flac -d -f -s -o chrono_2_21.wav "Chrono Trigger Symphony Vol 2 (FLAC)\21 - Burn_ Bobonga_ Burn_.flac"
flac -d -f -s -o chrono_2_22.wav "Chrono Trigger Symphony Vol 2 (FLAC)\22 - The Fiendlord_s Keep.flac"
flac -d -f -s -o chrono_2_23.wav "Chrono Trigger Symphony Vol 2 (FLAC)\23 - Strains of Insanity.flac"
flac -d -f -s -o chrono_2_24.wav "Chrono Trigger Symphony Vol 2 (FLAC)\24 - Magus Confronted.flac"

flac -d -f -s -o chrono_3_01.wav "Chrono Trigger Symphony Vol 3 (FLAC)\01 - Singing Mountain.flac"
flac -d -f -s -o chrono_3_02.wav "Chrono Trigger Symphony Vol 3 (FLAC)\02 - Tyrano Lair.flac"
flac -d -f -s -o chrono_3_03.wav "Chrono Trigger Symphony Vol 3 (FLAC)\03 - Depths of the Night.flac"
flac -d -f -s -o chrono_3_04.wav "Chrono Trigger Symphony Vol 3 (FLAC)\04 - Corridor of Time.flac"
flac -d -f -s -o chrono_3_05.wav "Chrono Trigger Symphony Vol 3 (FLAC)\05 - Zeal Palace.flac"
flac -d -f -s -o chrono_3_06.wav "Chrono Trigger Symphony Vol 3 (FLAC)\06 - Schala_s Theme.flac"
flac -d -f -s -o chrono_3_07.wav "Chrono Trigger Symphony Vol 3 (FLAC)\07 - Sealed Door.flac"
flac -d -f -s -o chrono_3_08.wav "Chrono Trigger Symphony Vol 3 (FLAC)\08 - Ocean Palace.flac"
flac -d -f -s -o chrono_3_09.wav "Chrono Trigger Symphony Vol 3 (FLAC)\09 - Crono _ Marle - A Distant Promise.flac"
flac -d -f -s -o chrono_3_10.wav "Chrono Trigger Symphony Vol 3 (FLAC)\10 - The Epoch - Wings of Time.flac"
flac -d -f -s -o chrono_3_11.wav "Chrono Trigger Symphony Vol 3 (FLAC)\11 - Black Omen.flac"
flac -d -f -s -o chrono_3_12.wav "Chrono Trigger Symphony Vol 3 (FLAC)\12 - Determination.flac"
flac -d -f -s -o chrono_3_13.wav "Chrono Trigger Symphony Vol 3 (FLAC)\13 - World Revolution.flac"
flac -d -f -s -o chrono_3_14.wav "Chrono Trigger Symphony Vol 3 (FLAC)\14 - The Final Battle.flac"
flac -d -f -s -o chrono_3_15.wav "Chrono Trigger Symphony Vol 3 (FLAC)\15 - Festival of Stars.flac"
flac -d -f -s -o chrono_3_16.wav "Chrono Trigger Symphony Vol 3 (FLAC)\16 - Epilogue - To My Dear Friends.flac"
flac -d -f -s -o chrono_3_17.wav "Chrono Trigger Symphony Vol 3 (FLAC)\17 - Outskirts of Time.flac"